### ISSUE TITLE
Do yourself a favor.....

### ISSUE THREAD

**Issue by cowboysdude** [justjim1220/MMM-MyVideoPlayer#2]
Go on google and research 

1.  Web friendly fonts
2.  Web friendly colors

**Comment by justjim1220** [comment]
OK, thanks for the heads up!
I guess I wasn't thinking about that. I used to build websites, so I should've known better.
I was setting things up for how I wanted them on my Mirror and didn't think about it.

BTW... It took me a minute, but I finally figured out the code I was asking you about.
I learned it on my own, so, wanted to say thanks for telling me it was possible and NOT doing it for me.
It made me use my brain to remember how things work. I feel like I am starting to get the gist of things. 😉

**Comment by justjim1220** [comment]
This module doesn't even have any funky fonts or colors encoded into it.

So, feels weird that you are saying something about it at this point.

But still, thanks for the heads up! 😉

**Comment by cowboysdude** [comment]
;)
