### ISSUE TITLE
issue #4 high video resolution causes CPU high utilization rate 

### ISSUE THREAD

**Issue by xuepgao** [justjim1220/MMM-MyVideoPlayer#9]
@justjim1220 

My config is as following:
```
		{
			module: "MMM-MyVideoPlayer",
			position: "middle_center",
			config:{
				initialLoadDelay: 5150,
				videoDir: "videos",
				posterDir: "posters",
				posterSize: {width:45, height:25},
				menuDirection: "row",
				playerSize: {width:640, height:360},
				playerBackground:"MM2splash.png"
		
				}
		},
```
If I adjust the value of **playerSize** to 1280x720  or I uploaded  a video file (which resolution is 1280x720) to play, the Raspberry CPU utilization rate will increase to 75% ~ 95%:
![image](https://user-images.githubusercontent.com/48181152/57070041-d90a2f00-6d08-11e9-8c7d-7d495b39e775.png)

When the module play a video which resolution is 640x360, the CPU utilization rate is about 35%.  In another word, this module only support to play low resolution video? How to optimize the codec ability of this module to reduce CPU utilization rate?

Thanks!

**Comment by justjim1220** [comment]
With Pi, you need the lower resolution because of the very issue you are experiencing.

Apologies. I have yet to figure out a solution for this issue.

**Comment by xuepgao** [comment]
OK. I got it.
